version: '3.8'

services:
  geth:
    image: ethereum/client-go:latest
    command:
      - --nat=extip:${EXTERNAL_IP}
      - --datadir=/root/.ethereum
      - --networkid=${CHAIN_ID}
      - --http
      - --http.addr=0.0.0.0
      - --http.port=${HTTP_PORT}
      - --http.api=eth,net,web3,personal,admin
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=${AUTHRPC_PORT}
      - --authrpc.jwtsecret=/root/.ethereum/jwt.hex
      - --syncmode=full
      - --port=${P2P_PORT}
    ports:
      - "${AUTHRPC_PORT}:${AUTHRPC_PORT}"
      - "${HTTP_PORT}:${HTTP_PORT}"
      - "${P2P_PORT}:${P2P_PORT}"
    volumes:
      - ./execution:/root/.ethereum/
      - ./jwt.hex:/root/.ethereum/jwt.hex

  beacon:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:latest
    command:
      - --datadir=/consensus/beacondata
      - --genesis-state=/consensus/genesis.ssz
      - --chain-config-file=/consensus/config.yml
      - --execution-endpoint=http://${EXTERNAL_IP}:${AUTHRPC_PORT}
      - --jwt-secret=/jwt.hex
      - --p2p-host-ip=${EXTERNAL_IP}
    depends_on:
      geth:
        condition: service_started
    ports:
      - "${RPC_PORT}:${RPC_PORT}"
      - "${P2P_TCP_PORT}:${P2P_TCP_PORT}"
      - "${P2P_UDP_PORT}:${P2P_UDP_PORT}/udp"
    volumes:
      - ./consensus:/consensus
      - ./jwt.hex:/jwt.hex

  validator:
    image: gcr.io/prysmaticlabs/prysm/validator:latest
    command:
      - --beacon-rpc-provider=${EXTERNAL_IP}:${RPC_PORT}
      - --datadir=/consensus/validatordata
      - --chain-config-file=/consensus/config.yml
      - --suggested-fee-recipient=0x${VALIDATOR_ADDRESS}
    depends_on:
      beacon:
        condition: service_started
    ports:
      - "${VALIDATOR_PORT}:${VALIDATOR_PORT}"
    volumes:
      - ./consensus:/consensus
